### ISSUE TITLE
Publish Database as Blog 

### ISSUE THREAD

**Issue by LinguList** [intercontinental-dictionary-series/keypano#24]
The plan is now that we publish the raw database with orthoprofiles with a blog post with [calcip](https://calc.hypohteses.org). This would enable us to refer to the data, make good use of it also for other projects, but also later put the borrowing annotation on top of it. @fractaldragonflies, I would prepare the publication here and also the blog post and we would submit this with you as first author if that is fine for you.

**Comment by LinguList** [comment]
The old status with additional code is now given in the tag v0.0.1, so nothing is lost.

**Comment by fractaldragonflies** [comment]
Plan sounds good to me...  time has value so getting our finished work out there makes much sense.  I've lost a sense of how much effort I put in readying the orthoprofiles, but it seems not so much compared to my investment in the borrowing annotation.  That said, with the effort you've put in and will contribute still for the publication and blog post, I would be content with you as first author and myself second.  Thanks Mattis.  Please let me know what I can do to help out on publication or post.

**Comment by FredericBlum** [comment]
Is the repo already in a state to release a version v0.1 that we can add to the upcoming Lexibank release?
