### ISSUE TITLE
Zenodo did not pick up the DOI 

### ISSUE THREAD

**Issue by LinguList** [intercontinental-dictionary-series/keypano#28]
The DOI in the release is from `idssegmented`. Do we plan a later release?

**Comment by LinguList** [comment]
@chrzyki and @FredericBlum, sorry having forgot to "ping" you here.

**Comment by FredericBlum** [comment]
Copy&paste error from my side, sorry. doi is now fixed.

**Comment by LinguList** [comment]
Thanks!
